export * from './transform';
export * from './spatial-index';
export * from './entity-bounds';
export * from './hit-test';
export { drawWall } from './render-wall';
export { EntityLayer } from './entity-layer';
export { createCanvasApp } from './canvas-app';
export type { CanvasHandle } from './canvas-app';
export type { SceneTool, ScenePointer } from './tool';
export { TR_CHARSET, ROOM_FONT } from './charset';
export { installRoomFont } from './room-font';
export { buildSpaceFill, buildSpaceLabel } from './render-space';
