export * from './transform';
export * from './spatial-index';
export * from './entity-bounds';
export * from './hit-test';
export { highlightEntity } from './highlight';
export { drawWall, buildWall, strokeWall } from './render-wall';
export { drawOpening } from './render-opening';
export { drawDimension, buildDimensionLabel } from './render-dimension';
export { drawParcel } from './render-parcel';
export { drawBlock } from './render-block';
export { buildAnnotation } from './render-annotation';
export { buildSheet } from './render-sheet';
export { drawSection, buildSectionLabels, layoutSectionLabels, SECTION_COLOR } from './render-section';
export { drawBlockSymbol } from './block-symbols';
export * from './linetypes';
export { EntityLayer } from './entity-layer';
export { LayerState } from './layer-state';
export { createSnapIndicator, type SnapHint, type SnapPointKind } from './snap-indicator';
export { createPresenceLayer, type RemoteCursor, type RemoteSelection } from './presence';
export { createCanvasApp } from './canvas-app';
export type { CanvasHandle } from './canvas-app';
export type { SceneTool, ScenePointer } from './tool';
export { TR_CHARSET, ROOM_FONT } from './charset';
export { installRoomFont } from './room-font';
export { buildSpaceFill, buildSpaceLabel, drawSpaceMaterial } from './render-space';
